language: ruby
rvm:
- 2.3.0
- 2.2.4
- 2.1.8
- 2.0.0
addons:
  code_climate:
    repo_token: $CODECLIMATE_REPO_TOKEN
before_install:
  - gem install bundler -v '~> 1.11'
gemfile:
  - gemfiles/40.gemfile
  - gemfiles/41.gemfile
  - gemfiles/42.gemfile
  - gemfiles/50.gemfile
matrix:
  exclude:
    - rvm: 2.0.0
      gemfile: gemfiles/50.gemfile
    - rvm: 2.1.8
      gemfile: gemfiles/50.gemfile
after_success:
  - bundle exec codeclimate-test-reporter
cache:
  - bundler
